name: Build
on:
  push:
    branches:
      - 'main'
      - 'ci/*'

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - run: yarn setup
      - run: yarn run compile
      - run: yarn run test:node:coverage
