name: Build
on:
  push:
    branches:
      - 'main'
      - 'ci/*'
      - 'next/*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - run: echo ${GITHUB_REF##*/}
      - run: echo "PACKAGE_DIR=${GITHUB_REF##*/}" >> $GITHUB_ENV
      - name: Set package version
        working-directory: ./${{ env.PACKAGE_DIR }}
        run: |
          PKG_VERSION=$(npx @siliconjungles/rn-scripts get_version_name)
          BUILD_NO=$GITHUB_RUN_NUMBER
          VERSION=$PKG_VERSION-next.$BUILD_NO
          npm version $VERSION --no-git-tag-version
      - name: Set package version
        working-directory: ./${{ env.PACKAGE_DIR }}
        run: cat package.json

  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - run: yarn setup
      - run: yarn run compile
      - run: yarn run test:node:coverage

  publish_next:
    if:  contains(github.ref, 'refs/heads/next')
    needs: [compile]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - run: echo ${GITHUB_REF##*/}
      - run: yarn setup

      - run: |
          PKG_VERSION=$(npx @siliconjungles/rn-scripts get_version_name)
          BUILD_NO=$GITHUB_RUN_NUMBER
          VERSION=$PKG_VERSION-next.$BUILD_NO
          npm version $VERSION --no-git-tag-version
      - run: npm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}
      - run: npm publish --access public --tag next
